created category model
indocom/pinus-server pull request #33
Opened 2021-03-07 13:50 UTC by ThePrevailingOne

2021-03-09 03:47 UTC, ryoarmanda requested changes
Good job! Two things that I need you to address:

- Don't delete the `.env.sample` file!
- Minor convention changes detailed on the review

2021-03-09 03:47 UTC, ryoarmanda commented on src/db/migrations/20210307133247-create-category.js
> +};
Can add a blank line after the last line here for convention

2021-03-13 18:17 UTC, ryoarmanda commented
Heads up that you need to pull the main branch, merge it to your PR branch, and resolve the conflicts first

2021-03-13 19:17 UTC, ThePrevailingOne commented
Oh right noted!

2021-03-13 19:27 UTC, ThePrevailingOne commented
Let me know kalo ada yg salah wkwkwk

2021-03-13 20:27 UTC, ryoarmanda requested changes

2021-03-13 20:27 UTC, ryoarmanda commented on src/db/migrations/20210307133247-create-category.js
> +    await queryInterface.createTable('Categories', {
Can you name the table in lowercase style? So it's `categories`

2021-03-13 20:27 UTC, ryoarmanda commented on src/db/migrations/20210307133247-create-category.js
> +    await queryInterface.dropTable('Categories');
Same here

2021-03-17 10:31 UTC, ThePrevailingOne commented
done!

2021-03-17 16:37 UTC, ryoarmanda approved these changes
LGTM!

2021-03-17 16:38 UTC, merged